input_features:
    -
        name: Time
        type: date
        encoder: wave
        preprocessing:
            datetime_format: "%Y-%m-%d %H:%M:%S"

    -
        name: Windowed_Open
        type: timeseries
        num_layers: 1
        dropout: 0.2
    -
        name: Windowed_High
        type: timeseries
        num_layers: 1
        dropout: 0.2    
    -
        name: Windowed_Low
        type: timeseries
        num_layers: 1
        dropout: 0.2
output_features:
    -
        name: Label1
        type: numerical

        

training:
  learning_rate: 0.001
  batch_size: 64
