input_features:
    -
        name: Time
        type: date
        preprocessing
        datetime_format: "%Y-%m-%d %H:%M:%S"

    -
        name: Timeseries_Windowed
        type: timeseries
        encoder: rnn
        num_layers: 1
    -
        name: Open
        type: numerical
        
    -
        name: High
        type: numerical
    -
        name: Low
        type: numerical

    -
        name: Close
        type: numerical

output_features:
    -
        name: Label1
        type: numerical
    -
        name: Label2
        type: numerical
    -
        name: Label3
        type: numerical
        

training:
  learning_rate: 0.001
  optimizer:
    type: sgd
    
