input_features:
    -
        name: Timeseries_Windowed
        type: timeseries
        encoder: rnn
        num_layers: 1
    -
        name: Open
        type: numerical
        
    -
        name: High
        type: numerical
    -
        name: Low
        type: numerical

    -
        name: Close
        type: numerical

output_features:
    -
        name: Label1
        type: numerical
       

training:
  learning_rate: 0.001
  batch_size: 24
  
    
    
