input_features:
    -
        name: Time
        type: date
        encoder: wave
        preprocessing:
            datetime_format: "%Y-%m-%d %H:%M:%S"

    -
        name: High.1
        type: timeseries
        encoder: rnn
        num_layers: 1
        dropout: 0.2
    -
        name: Low.1
        type: numerical

    -
        name: Close.1
        type: numerical

output_features:
    -
        name: Label1
        type: numerical

        

training:
  learning_rate: 0.001
  batch_size: 6
  
    
